[build]
target = "thumbv6m-none-eabi"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[target.thumbv6m-none-eabi]
runner = "elf2uf2-rs -d"
